# Generated by Django 3.0.8 on 2021-05-31 17:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('for_day', models.DateField(error_messages={'blank': "The for_day field can't be blank.", 'invalid': 'The for_day field is invalid.', 'null': "The for_day field can't be null."}, verbose_name='For day')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
                'db_table': 'menu',
                'ordering': ('for_day',),
                'abstract': False,
                'unique_together': {('for_day',)},
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('option_num', models.IntegerField(error_messages={'blank': "The option_num field can't be blank.", 'invalid': 'The option_num field is invalid.', 'null': "The option_num field can't be null."}, verbose_name='Option number')),
                ('description', models.CharField(error_messages={'blank': "The description field can't be blank.", 'invalid': 'The description field is invalid.', 'max_length': 'The description field must be at most 255 characters.', 'null': "The description field can't be null."}, max_length=255, verbose_name='Description')),
                ('menu', models.ForeignKey(error_messages={'blank': "The items field can't be blank.", 'invalid': 'The items field is invalid.', 'null': "The items field can't be null."}, on_delete=django.db.models.deletion.CASCADE, to='meal_delivery.Menu', verbose_name='Menu')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menus Items',
                'db_table': 'menu_item',
                'ordering': ('option_num',),
                'abstract': False,
                'unique_together': {('menu', 'option_num')},
            },
        ),
    ]
